export const hotels = [
  {
    id: "azure-cliff-santorini",
    name: "Azure Cliff Villas",
    location: "Santorini, Greece",
    rating: 4.9,
    reviews: 812,
    price: 320,
    category: "Luxury",
    amenities: ["Infinity Pool", "Free WiFi", "Breakfast Included", "Spa", "Sea View"],
    image: "https://images.unsplash.com/photo-1602391833977-358a52198938?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "ubud-jungle-retreat",
    name: "Ubud Jungle Retreat",
    location: "Bali, Indonesia",
    rating: 4.7,
    reviews: 634,
    price: 145,
    category: "Boutique",
    amenities: ["Free WiFi", "Pool", "Yoga Studio", "Breakfast Included"],
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "kyoto-machiya-inn",
    name: "Kyoto Machiya Inn",
    location: "Kyoto, Japan",
    rating: 4.8,
    reviews: 421,
    price: 210,
    category: "Traditional",
    amenities: ["Free WiFi", "Onsen Bath", "Tea Ceremony", "Garden View"],
    image: "https://images.unsplash.com/photo-1578469645742-46cae010e5d4?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "alpine-chalet-zermatt",
    name: "Alpine Chalet Zermatt",
    location: "Swiss Alps, Switzerland",
    rating: 4.6,
    reviews: 298,
    price: 380,
    category: "Luxury",
    amenities: ["Fireplace", "Free WiFi", "Ski-in/Ski-out", "Spa", "Mountain View"],
    image: "https://images.unsplash.com/photo-1517320964276-a002fa203177?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "medina-riad-marrakech",
    name: "Riad Al Yasmine",
    location: "Marrakech, Morocco",
    rating: 4.5,
    reviews: 356,
    price: 95,
    category: "Boutique",
    amenities: ["Rooftop Pool", "Free WiFi", "Breakfast Included", "Courtyard"],
    image: "https://images.unsplash.com/photo-1553603227-2358aabe821e?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "overwater-bungalow-maldives",
    name: "Coral Lagoon Overwater Villas",
    location: "Maldives",
    rating: 4.9,
    reviews: 703,
    price: 620,
    category: "Luxury",
    amenities: ["Private Pool", "Overwater Deck", "Free WiFi", "All-Inclusive", "Butler Service"],
    image: "https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?q=80&w=1200&auto=format&fit=crop",
  },
];

export const hotelCategories = ["All", "Luxury", "Boutique", "Traditional"];
